
export enum GameType {
  CASUAL = 'casual',
  FARMING = 'farming',
  MYTHICAL_CARD = 'mythical-card',
}

export enum CardStat {
  STR = 'strength',
  ACC = 'acceleration',
  JMP = 'jump',
  POW = 'power',
  PRE = 'presence',
  END = 'endurance',
  QUI = 'quickness',
  CAR = 'carry'
}

export const currentDate = new Date();
export const yesterdayDate = new Date((new Date()).setDate(currentDate.getDate() - 1));
export const tomorrowDate = new Date((new Date()).setDate(currentDate.getDate() + 1));
export const prevYearDate = new Date((new Date()).setFullYear(currentDate.getFullYear() - 1));
export const nextYearDate = new Date((new Date()).setFullYear(currentDate.getFullYear() + 1));

export const GAME_DATA = {
  id: 1,
  name: 'NFL Rival Game',
  gameType: GameType.MYTHICAL_CARD,
  documentId: 'game_01',
  description: 'Demo Game',
  url: '',
  maxEnergy: 300,
  slug: 'nfl_rival_game',
  active: true,
  maxPoint: 1000,
  energyPerGame: 0,
  pointConversionRate: 1,
  maxPointPerGame: 0,
  icon: '',
  rank_definition: '[]',
  banner: '',
  startTime: prevYearDate,
  endTime: nextYearDate,
};

export const GAME_EVENTS = {
  id: 0,
  documentId: 'event_01',
  name: 'Demo Event 01',
  game: {
    documentId: GAME_DATA.documentId,
  },
  gameId: 1,
  icon: '',
  description: '',
  startTime: yesterdayDate,
  endTime: nextYearDate,
  tossUpInfo: {
    stats: [CardStat.ACC, CardStat.PRE, CardStat.JMP, CardStat.POW],
    opponent_teams: [],
    round: 3,
    difficulty: 6,
    playDuration: 180,
    gameplayPerEvent: 2,
  },
  tossUpBonus: [
    {
      __component: 'mythical.team-bonus',
      program: 'halloween_2023',
      bonus: 5,
      bonusText: 'Program Bonus 5%',
    },
    {
      __component: 'mythical.team-bonus',
      position: 'FS',
      bonus: 5,
      bonusText: 'Position FS 5%',
    },
  ],
};


export const CARD_USER_START = [
  {
    defId: "1cstroud7te1",
    firstName: "C.J.",
    lastName: "Stroud",
    team: "texans",
    position: "QB",
    rarity: "epic",
    card: "default",
    stars: 3,
    level: 1,
    power: 81,
    strength: 52,
    quickness: 64,
    acceleration: 53,
    presence: 83,
    endurance: 80,
    jump: 54,
    carry: 51,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/C.J._Stroud.png"
  },
  {
    defId: "1baiyuk11ft1",
    firstName: "Brandon",
    lastName: "Aiyuk",
    team: "fourty_niners",
    position: "WR",
    rarity: "epic",
    card: "default",
    stars: 3,
    level: 1,
    power: 80,
    strength: 54,
    quickness: 101,
    acceleration: 91,
    presence: 54,
    endurance: 59,
    jump: 113,
    carry: 69,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Brandon_Aiyuk.png"
  },
  {
    defId: "1jelliott4ea1",
    firstName: "Jake",
    lastName: "Elliott",
    team: "eagles",
    position: "K",
    rarity: "rare",
    card: "default",
    stars: 2,
    level: 1,
    power: 80,
    strength: 27,
    quickness: 42,
    acceleration: 60,
    presence: 26,
    endurance: 54,
    jump: 38,
    carry: 29,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Jake_Elliott.png"
  },
  {
    defId: "1jferguson65cw1",
    firstName: "Jake",
    lastName: "Ferguson",
    team: "cowboys",
    position: "TE",
    rarity: "common",
    card: "default",
    stars: 1,
    level: 1,
    power: 68,
    strength: 56,
    quickness: 61,
    acceleration: 52,
    presence: 65,
    endurance: 87,
    jump: 65,
    carry: 65,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Jake_Ferguson.png"
  },
  {
    defId: "1qwilliams56je1",
    firstName: "Quincy",
    lastName: "Williams",
    team: "jets",
    position: "LB",
    rarity: "common",
    card: "default",
    stars: 1,
    level: 1,
    power: 68,
    strength: 56,
    quickness: 65,
    acceleration: 75,
    presence: 49,
    endurance: 61,
    jump: 84,
    carry: 40,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Quincy_Williams.png"
  },
  {
    defId: "1xmckinney29gi1",
    firstName: "Xavier",
    lastName: "McKinney",
    team: "packers",
    position: "FS",
    rarity: "rare",
    card: "default",
    stars: 2,
    level: 1,
    power: 71,
    strength: 58,
    quickness: 84,
    acceleration: 75,
    presence: 57,
    endurance: 80,
    jump: 85,
    carry: 57,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Xavier_McKinney.png"
  },
  {
    defId: "1charrisj25fr1",
    firstName: "Chris",
    lastName: "Harris Jr",
    team: "free_agent",
    position: "CB",
    rarity: "rare",
    card: "default",
    stars: 2,
    level: 1,
    power: 79,
    strength: 44,
    quickness: 97,
    acceleration: 71,
    presence: 67,
    endurance: 94,
    jump: 92,
    carry: 51,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Chris_Harris_Jr.png"
  },
  {
    defId: "1xrhodes27fr1",
    firstName: "Xavier",
    lastName: "Rhodes",
    team: "free_agent",
    position: "CB",
    rarity: "rare",
    card: "default",
    stars: 2,
    level: 1,
    power: 78,
    strength: 63,
    quickness: 83,
    acceleration: 70,
    presence: 64,
    endurance: 90,
    jump: 100,
    carry: 59,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Xavier_Rhodes.png"
  },
  {
    defId: "1jjohnson33br1",
    firstName: "Jaylon",
    lastName: "Johnson",
    team: "bears",
    position: "CB",
    rarity: "rare",
    card: "default",
    stars: 2,
    level: 1,
    power: 76,
    strength: 52,
    quickness: 76,
    acceleration: 72,
    presence: 64,
    endurance: 83,
    jump: 88,
    carry: 52,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Jaylon_Johnson.png"
  },
  {
    defId: "1dparham85ch9",
    firstName: "Donald",
    lastName: "Parham Jr",
    team: "chargers",
    position: "TE",
    rarity: "rare",
    card: "gridiron_standouts_2023",
    stars: 2,
    level: 1,
    power: 99,
    strength: 107,
    quickness: 91,
    acceleration: 86,
    presence: 85,
    endurance: 111,
    jump: 106,
    carry: 77,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/9/Donald_Parham_Jr.png"
  },
  {
    defId: "1cflott28gi1",
    firstName: "Cor'Dale",
    lastName: "Flott",
    team: "giants",
    position: "CB",
    rarity: "common",
    card: "default",
    stars: 1,
    level: 1,
    power: 65,
    strength: 65,
    quickness: 65,
    acceleration: 65,
    presence: 65,
    endurance: 65,
    jump: 65,
    carry: 65,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Cor'Dale_Flott.png"
  },
  {
    defId: "1epineiro4pn1",
    firstName: "Eddy",
    lastName: "Pineiro",
    team: "panthers",
    position: "K",
    rarity: "epic",
    card: "default",
    stars: 3,
    level: 1,
    power: 85,
    strength: 35,
    quickness: 37,
    acceleration: 36,
    presence: 48,
    endurance: 73,
    jump: 69,
    carry: 32,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Eddy_Pineiro.png"
  },
  {
    defId: "1tcampbell32ja1",
    firstName: "Tyson",
    lastName: "Campbell",
    team: "jaguars",
    position: "CB",
    rarity: "epic",
    card: "default",
    stars: 3,
    level: 1,
    power: 85,
    strength: 52,
    quickness: 94,
    acceleration: 99,
    presence: 64,
    endurance: 81,
    jump: 92,
    carry: 34,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Tyson_Campbell.png"
  },
  {
    defId: "1jmckissic41cm1",
    firstName: "J.D.",
    lastName: "McKissic",
    team: "free_agent",
    position: "RB",
    rarity: "rare",
    card: "default",
    stars: 2,
    level: 1,
    power: 79,
    strength: 60,
    quickness: 101,
    acceleration: 81,
    presence: 54,
    endurance: 73,
    jump: 94,
    carry: 91,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/J.D._McKissic.png"
  },
  {
    defId: "1dleal98sl1",
    firstName: "DeMarvin",
    lastName: "Leal",
    team: "steelers",
    position: "DE",
    rarity: "common",
    card: "default",
    stars: 1,
    level: 1,
    power: 65,
    strength: 65,
    quickness: 65,
    acceleration: 65,
    presence: 65,
    endurance: 65,
    jump: 65,
    carry: 65,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/DeMarvin_Leal.png"
  },
  {
    defId: "1dpettis13br1",
    firstName: "Dante",
    lastName: "Pettis",
    team: "bears",
    position: "WR",
    rarity: "rare",
    card: "default",
    stars: 2,
    level: 1,
    power: 77,
    strength: 38,
    quickness: 111,
    acceleration: 92,
    presence: 37,
    endurance: 57,
    jump: 103,
    carry: 75,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Dante_Pettis.png"
  },
  {
    defId: "1jezeudu75gi1",
    firstName: "Joshua",
    lastName: "Ezeudu",
    team: "giants",
    position: "OL",
    rarity: "common",
    card: "default",
    stars: 1,
    level: 1,
    power: 65,
    strength: 65,
    quickness: 65,
    acceleration: 65,
    presence: 65,
    endurance: 65,
    jump: 65,
    carry: 65,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Joshua_Ezeudu.png"
  },
  {
    defId: "1mlewis89pc1",
    firstName: "Marcedes",
    lastName: "Lewis",
    team: "bears",
    position: "TE",
    rarity: "common",
    card: "default",
    stars: 1,
    level: 1,
    power: 67,
    strength: 79,
    quickness: 53,
    acceleration: 51,
    presence: 53,
    endurance: 68,
    jump: 92,
    carry: 85,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Marcedes_Lewis.png"
  },
  {
    defId: "1sgriffin26ja1",
    firstName: "Shaquill",
    lastName: "Griffin",
    team: "vikings",
    position: "CB",
    rarity: "rare",
    card: "default",
    stars: 2,
    level: 1,
    power: 79,
    strength: 56,
    quickness: 84,
    acceleration: 86,
    presence: 56,
    endurance: 77,
    jump: 95,
    carry: 61,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Shaquill_Griffin.png"
  },
  {
    defId: "1ahicks96bu1",
    firstName: "Akiem",
    lastName: "Hicks",
    team: "free_agent",
    position: "DT",
    rarity: "rare",
    card: "default",
    stars: 2,
    level: 1,
    power: 79,
    strength: 105,
    quickness: 42,
    acceleration: 46,
    presence: 69,
    endurance: 52,
    jump: 71,
    carry: 29,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Akiem_Hicks.png"
  },
  {
    defId: "1tedmunds49bl1",
    firstName: "Tremaine",
    lastName: "Edmunds",
    team: "bears",
    position: "LB",
    rarity: "epic",
    card: "default",
    stars: 3,
    level: 1,
    power: 82,
    strength: 72,
    quickness: 88,
    acceleration: 71,
    presence: 75,
    endurance: 64,
    jump: 80,
    carry: 38,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Tremaine_Edmunds.png"
  },
  {
    defId: "1acappa65bn1",
    firstName: "Alex",
    lastName: "Cappa",
    team: "bengals",
    position: "OL",
    rarity: "rare",
    card: "default",
    stars: 2,
    level: 1,
    power: 71,
    strength: 94,
    quickness: 37,
    acceleration: 41,
    presence: 88,
    endurance: 86,
    jump: 61,
    carry: 42,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Alex_Cappa.png"
  },
  {
    defId: "1gdulcich80bc1",
    firstName: "Greg",
    lastName: "Dulcich",
    team: "broncos",
    position: "TE",
    rarity: "common",
    card: "default",
    stars: 1,
    level: 1,
    power: 65,
    strength: 64,
    quickness: 64,
    acceleration: 64,
    presence: 64,
    endurance: 64,
    jump: 64,
    carry: 64,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Greg_Dulcich.png"
  },
  {
    defId: "1jkelley27cg1",
    firstName: "Joshua",
    lastName: "Kelley",
    team: "chargers",
    position: "RB",
    rarity: "rare",
    card: "default",
    stars: 2,
    level: 4,
    power: 81,
    strength: 73,
    quickness: 81,
    acceleration: 72,
    presence: 48,
    endurance: 58,
    jump: 83,
    carry: 98,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Joshua_Kelley.png"
  },
  {
    defId: "1tlewan77ti1",
    firstName: "Taylor",
    lastName: "Lewan",
    team: "free_agent",
    position: "OL",
    rarity: "epic",
    card: "default",
    stars: 3,
    level: 3,
    power: 87,
    strength: 100,
    quickness: 48,
    acceleration: 58,
    presence: 89,
    endurance: 81,
    jump: 70,
    carry: 35,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Taylor_Lewan.png"
  },
  {
    defId: "1ejackson4br1",
    firstName: "Eddie",
    lastName: "Jackson",
    team: "ravens",
    position: "FS",
    rarity: "epic",
    card: "default",
    stars: 3,
    level: 4,
    power: 86,
    strength: 51,
    quickness: 85,
    acceleration: 82,
    presence: 90,
    endurance: 78,
    jump: 88,
    carry: 72,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Eddie_Jackson.png"
  },
  {
    defId: "1mprater5cd1",
    firstName: "Matt",
    lastName: "Prater",
    team: "cardinals",
    position: "K",
    rarity: "epic",
    card: "default",
    stars: 3,
    level: 5,
    power: 88,
    strength: 32,
    quickness: 26,
    acceleration: 41,
    presence: 33,
    endurance: 37,
    jump: 29,
    carry: 33,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Matt_Prater.png"
  },
  {
    defId: "1lcollins71bn1",
    firstName: "La'el",
    lastName: "Collins",
    team: "bills",
    position: "OL",
    rarity: "epic",
    card: "default",
    stars: 3,
    level: 5,
    power: 88,
    strength: 99,
    quickness: 36,
    acceleration: 37,
    presence: 106,
    endurance: 62,
    jump: 56,
    carry: 31,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/La'el_Collins.png"
  },
  {
    defId: "1pjonesii91vi1",
    firstName: "Patrick",
    lastName: "Jones II",
    team: "vikings",
    position: "DE",
    rarity: "common",
    card: "default",
    stars: 1,
    level: 5,
    power: 76,
    strength: 87,
    quickness: 54,
    acceleration: 58,
    presence: 53,
    endurance: 50,
    jump: 81,
    carry: 39,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Patrick_Jones_II.png"
  },
  {
    defId: "1nscott33bn1",
    firstName: "Nick",
    lastName: "Scott",
    team: "panthers",
    position: "FS",
    rarity: "common",
    card: "default",
    stars: 1,
    level: 5,
    power: 76,
    strength: 50,
    quickness: 95,
    acceleration: 85,
    presence: 58,
    endurance: 80,
    jump: 99,
    carry: 56,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Nick_Scott.png"
  },
  {
    defId: "1hvaltal1li1",
    firstName: "Halapoulivaati",
    lastName: "Vaitai",
    team: "lions",
    position: "OL",
    rarity: "rare",
    card: "default",
    stars: 2,
    level: 3,
    power: 76,
    strength: 89,
    quickness: 28,
    acceleration: 37,
    presence: 92,
    endurance: 45,
    jump: 64,
    carry: 33,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Halapoulivaati_Vaitai.png"
  },
  {
    defId: "2jjacobs28ri20",
    firstName: "Josh",
    lastName: "Jacobs",
    team: "packers",
    position: "RB",
    rarity: "legendary",
    card: "roadtoplayoffs24",
    stars: 4,
    level: 16,
    power: 158,
    strength: 148,
    quickness: 155,
    acceleration: 160,
    presence: 127,
    endurance: 184,
    jump: 109,
    carry: 183,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/20/Josh_Jacobs.png"
  },
  {
    defId: "2jhurts1ea21",
    firstName: "Jalen",
    lastName: "Hurts",
    team: "eagles",
    position: "QB",
    rarity: "legendary",
    card: "kickoff24",
    stars: 4,
    level: 15,
    power: 158,
    strength: 137,
    quickness: 155,
    acceleration: 159,
    presence: 140,
    endurance: 130,
    jump: 146,
    carry: 110,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/21/Jalen_Hurts.png"
  },
  {
    defId: "1bwagner54sh7",
    firstName: "Bobby",
    lastName: "Wagner",
    team: "seahawks",
    position: "LB",
    rarity: "mythical",
    card: "nfl_shakers_2023",
    stars: 5,
    level: 7,
    power: 157,
    strength: 162,
    quickness: 124,
    acceleration: 120,
    presence: 189,
    endurance: 129,
    jump: 135,
    carry: 77,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/7/Bobby_Wagner.png"
  },
  {
    defId: "1dmetcalf14sh15",
    firstName: "DK",
    lastName: "Metcalf",
    team: "seahawks",
    position: "WR",
    rarity: "mythical",
    card: "combine_2024",
    stars: 5,
    level: 25,
    power: 184,
    strength: 149,
    quickness: 154,
    acceleration: 187,
    presence: 166,
    endurance: 148,
    jump: 211,
    carry: 142,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/15/DK_Metcalf.png"
  },
  {
    defId: "1ahighsmit56sl11",
    firstName: "Alex",
    lastName: "Highsmith",
    team: "steelers",
    position: "DE",
    rarity: "epic",
    card: "autumn_rush_2023",
    stars: 3,
    level: 4,
    power: 124,
    strength: 107,
    quickness: 103,
    acceleration: 105,
    presence: 132,
    endurance: 86,
    jump: 139,
    carry: 49,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/11/Alex_Highsmith.png"
  },
  {
    defId: "1mgoodwin3br13",
    firstName: "Marquise",
    lastName: "Goodwin",
    team: "bears",
    position: "WR",
    rarity: "rare",
    card: "cold_snap_2023",
    stars: 2,
    level: 10,
    power: 124,
    strength: 48,
    quickness: 145,
    acceleration: 139,
    presence: 76,
    endurance: 92,
    jump: 145,
    carry: 119,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/13/Marquise_Goodwin_snow_day.png"
  },
  {
    defId: "1eelliott21cw1",
    firstName: "Ezekiel",
    lastName: "Elliott",
    team: "cowboys",
    position: "RB",
    rarity: "epic",
    card: "default",
    stars: 3,
    level: 1,
    power: 85,
    strength: 74,
    quickness: 96,
    acceleration: 81,
    presence: 84,
    endurance: 105,
    jump: 108,
    carry: 80,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Ezekiel_Elliott.png"
  },
  {
    defId: "1zsmith55vi1",
    firstName: "Za'Darius",
    lastName: "Smith",
    team: "browns",
    position: "DE",
    rarity: "epic",
    card: "default",
    stars: 3,
    level: 1,
    power: 85,
    strength: 81,
    quickness: 61,
    acceleration: 72,
    presence: 79,
    endurance: 64,
    jump: 77,
    carry: 34,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Za'Darius_Smith.png"
  },
  {
    defId: "1jhicks58vi1",
    firstName: "Jordan",
    lastName: "Hicks",
    team: "browns",
    position: "LB",
    rarity: "epic",
    card: "default",
    stars: 3,
    level: 4,
    power: 84,
    strength: 86,
    quickness: 85,
    acceleration: 82,
    presence: 75,
    endurance: 78,
    jump: 78,
    carry: 54,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Jordan_Hicks.png"
  },
  {
    defId: "1jalt76fr1",
    firstName: "Joe",
    lastName: "Alt",
    team: "chargers",
    position: "OL",
    rarity: "epic",
    card: "default",
    stars: 3,
    level: 3,
    power: 84,
    strength: 106,
    quickness: 59,
    acceleration: 49,
    presence: 53,
    endurance: 73,
    jump: 69,
    carry: 31,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Joe_Alt.png"
  },
  {
    defId: "1fluvu49pn1",
    firstName: "Frankie",
    lastName: "Luvu",
    team: "commanders",
    position: "LB",
    rarity: "epic",
    card: "default",
    stars: 3,
    level: 3,
    power: 85,
    strength: 85,
    quickness: 65,
    acceleration: 64,
    presence: 99,
    endurance: 67,
    jump: 72,
    carry: 40,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Frankie_Luvu.png"
  },
  {
    defId: "1jgaroppol10ri7",
    firstName: "Jimmy",
    lastName: "Garoppolo",
    team: "raiders",
    position: "QB",
    rarity: "rare",
    card: "nfl_shakers_2023",
    stars: 2,
    level: 7,
    power: 106,
    strength: 74,
    quickness: 84,
    acceleration: 68,
    presence: 76,
    endurance: 100,
    jump: 100,
    carry: 77,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/7/Jimmy_Garoppolo.png"
  },
  {
    defId: "1twatt90sl13",
    firstName: "T.J.",
    lastName: "Watt",
    team: "steelers",
    position: "DE",
    rarity: "mythical",
    card: "cold_snap_2023",
    stars: 5,
    level: 7,
    power: 157,
    strength: 137,
    quickness: 135,
    acceleration: 141,
    presence: 155,
    endurance: 112,
    jump: 143,
    carry: 66,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/13/T.J._Watt.png"
  },
  {
    defId: "1dcampbell59pc16",
    firstName: "De'Vondre",
    lastName: "Campbell",
    team: "falcons",
    position: "LB",
    rarity: "legendary",
    card: "nfl_draft_2024",
    stars: 4,
    level: 19,
    power: 157,
    strength: 138,
    quickness: 151,
    acceleration: 132,
    presence: 154,
    endurance: 116,
    jump: 126,
    carry: 60,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/16/De_Vondre_Campbell.png"
  }
]


export const CardOpponent = [
  {
    defId: "1jkelley27cg17",
    firstName: "Joshua",
    lastName: "Kelley",
    team: "chargers",
    position: "RB",
    rarity: "rare",
    card: "poty_2024",
    stars: 2,
    level: 1,
    power: 103,
    strength: 91,
    quickness: 104,
    acceleration: 95,
    presence: 78,
    endurance: 73,
    jump: 104,
    carry: 109,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/17/Joshua_Kelley.png"
  },
  {
    defId: "1jkelley27cg17",
    firstName: "Joshua",
    lastName: "Kelley",
    team: "chargers",
    position: "RB",
    rarity: "rare",
    card: "poty_2024",
    stars: 2,
    level: 2,
    power: 105,
    strength: 97,
   quickness: 104,
    acceleration: 101,
    presence: 78,
    endurance: 78,
    jump: 104,
    carry: 109,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/17/Joshua_Kelley.png"
  },
  {
    defId: "1jkelley27cg17",
    firstName: "Joshua",
    lastName: "Kelley",
    team: "chargers",
    position: "RB",
    rarity: "rare",
    card: "poty_2024",
    stars: 2,
    level: 3,
    power: 107,
    strength: 97,
   quickness: 104,
    acceleration: 101,
    presence: 83,
    endurance: 78,
    jump: 111,
    carry: 109,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/17/Joshua_Kelley.png"
  },
  {
    defId: "1jkelley27cg17",
    firstName: "Joshua",
    lastName: "Kelley",
    team: "chargers",
    position: "RB",
    rarity: "rare",
    card: "poty_2024",
    stars: 2,
    level: 4,
    power: 110,
    strength: 97,
   quickness: 112,
    acceleration: 101,
    presence: 83,
    endurance: 78,
    jump: 111,
    carry: 118,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/17/Joshua_Kelley.png"
  },
  {
    defId: "1jkelley27cg17",
    firstName: "Joshua",
    lastName: "Kelley",
    team: "chargers",
    position: "RB",
    rarity: "rare",
    card: "poty_2024",
    stars: 2,
    level: 5,
    power: 112,
    strength: 97,
   quickness: 112,
    acceleration: 108,
    presence: 83,
    endurance: 83,
    jump: 111,
    carry: 118,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/17/Joshua_Kelley.png"
  },
  {
   defId: "1epineiro4pn1",
    firstName: "Eddy",
    lastName: "Pineiro",
    team: "panthers",
    position: "K",
    rarity: "epic",
    card: "default",
    stars: 3,
    level: 2,
    power: 86,
    strength: 36,
    quickness: 37,
    acceleration: 36,
    presence: 48,
    endurance: 74,
    jump: 70,
    carry: 32,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Eddy_Pineiro.png"
  },
  {
    defId: "1jkelley27cg17",
    firstName: "Joshua",
    lastName: "Kelley",
    team: "chargers",
    position: "RB",
    rarity: "rare",
    card: "poty_2024",
    stars: 2,
    level: 7,
    power: 116,
    strength: 103,
   quickness: 116,
    acceleration: 108,
    presence: 88,
    endurance: 83,
    jump: 118,
    carry: 122,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/17/Joshua_Kelley.png"
  },
  {
    defId: "1lwallace39sl9",
    firstName: "Levi",
    lastName: "Wallace",
    team: "steelers",
    position: "CB",
    rarity: "epic",
    card: "gridiron_standouts_2023",
    stars: 3,
    level: 6,
    power: 124,
    strength: 75,
    quickness: 131,
    acceleration: 138,
    presence: 123,
    endurance: 110,
    jump: 125,
    carry: 70,
    image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/9/Levi_Wallace.png"
  }
]

export const StateData = {
  cardOpponents: CardOpponent,
  rounds: [
    {
      roundNumber: 1,
      stats: [[CardStat.ACC], [CardStat.PRE]],
      state: 'idle',
      difficulty: 7,
      idealStat: { [CardStat.ACC]: 10 },
      score: 0,
      cardOpponent: {
        defId: "1jkelley27cg17",
        firstName: "Joshua",
        lastName: "Kelley",
        team: "chargers",
        position: "RB",
        rarity: "rare",
        card: "poty_2024",
        stars: 2,
        level: 8,
        power: 118,
        strength: 109,
        quickness: 116,
        acceleration: 114,
        presence: 88,
        endurance: 88,
        jump: 118,
        carry: 122,
        image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/17/Joshua_Kelley.png"
      }
    },
    {
      roundNumber: 2,
      stats: [[CardStat.JMP], [CardStat.POW]],
      state: 'idle',
      difficulty: 6.5,
      idealStat: { [CardStat.JMP]: 10 },
      score: 0,
      cardOpponent:   {
        defId: "1lwallace39sl9",
        firstName: "Levi",
        lastName: "Wallace",
        team: "steelers",
        position: "CB",
        rarity: "epic",
        card: "gridiron_standouts_2023",
        stars: 3,
        level: 6,
        power: 124,
        strength: 75,
        quickness: 131,
        acceleration: 138,
        presence: 123,
        endurance: 110,
        jump: 125,
        carry: 70,
        image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/9/Levi_Wallace.png"
      }
    },
    {
      roundNumber: 3,
      stats: [[CardStat.ACC, CardStat.JMP], [CardStat.PRE, CardStat.POW]],
      state: 'idle',
      difficulty: 6,
      idealStat: { [CardStat.ACC]: 10, [CardStat.JMP]: 10 },
      score: 0,
      cardOpponent:   {
        defId: "1epineiro4pn1",
        firstName: "Eddy",
        lastName: "Pineiro",
        team: "panthers",
        position: "K",
        rarity: "epic",
        card: "default",
        stars: 3,
        level: 2,
        power: 86,
        strength: 36,
        quickness: 37,
        acceleration: 36,
        presence: 48,
        endurance: 74,
        jump: 70,
        carry: 32,
        image: "https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Eddy_Pineiro.png"
      },
    }
  ]
}

export const GameInitData = {
  id: Math.floor(Math.random() * 1000),
  accountId: 'p1',
  gameDataId: 1,
  startTime: new Date(),
  endTime: new Date(),
  score: 0,
  gamePoint: 0,
  ratio: 0,
  success: true,
  state: '',
  stateData: {...StateData}
}

